name: go test coverage

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]

permissions:
  # Required: allow read access to the content for analysis.
  contents: read

jobs:
  go-test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
  
      - name: generate test coverage
        run: go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...

      - name: check test coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          # Configure action using config file (option 1)
          config: ./.testcoverage.yml
