name: lint repo

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]

jobs:
  lint-code-base:
    uses: senzing-factory/build-resources/.github/workflows/linter.yaml@v1
    with:
      validate-all-codebase: true
